services:
  api:
    build:
      dockerfile: api.dockerfile
      context: .
    container_name: ${NOME_CONTAINER_API}
    networks:
      - base_network
    ports:
      - "${PORTA_API_HOST}:${PORTA_API_CONTAINER}"
      - "${PORTA_PRISMA}:${PORTA_PRISMA}"
    expose:
      - ${PORTA_API_CONTAINER}
    volumes:
      - "${DIRETORIO_HOST}:${DIRETORIO_CONTAINER}"
      - /api/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"
    environment:
      - DB=${NOME_CONTAINER_BD}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}

  mysql:
    networks:
      - base_network
    image: ${IMAGEM_BD}
    container_name: ${NOME_CONTAINER_BD}
    ports:
      - "${PORTA_BD_HOST}:${PORTA_BD_CONTAINER}"
    volumes:
      - ${NOME_VOLUME_BD}
    expose:
      - ${PORTA_BD_HOST}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

networks:
  base_network:
    driver: bridge

volumes:
  my_db: