services:
  backend:
    build:
      context: api
    container_name: backend
    command: npm start
    volumes:
      - ./api:/usr/src/app
    tty: true
    ports:
      - "3030:3030"
    networks:
      - solutions_one_network
    env_file:
      - ./api/.env

  frontend:
    build:
      context: client
    container_name: frontend
    command: npm run dev
    volumes:
      - ./client:/usr/src/app
    tty: true
    ports:
      - "5173:5173"
    networks:
      - solutions_one_network


  postgres:
    build:
      context: ./database
    container_name: postgres
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solutions_one_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./database/.env
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - solutions_one_network

networks:
  solutions_one_network:
    name: solutions_one_network
    driver: bridge

volumes:
  postgres_data: